name: xremit
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.0+2

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  get: ^4.6.1
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^3.0.1
  flutter_svg: ^1.0.3
  pin_code_fields: ^7.1.0
  country_code_picker: ^2.0.2

  get_storage:
  image_picker: ^0.8.5+3
  share_plus: ^4.1.0
  r_dotted_line_border: ^0.1.1
  file_picker: ^5.0.1
  intl: ^0.17.0

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  change_app_package_name: ^1.1.0
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Logo/Fav-icon.png"

flutter_app_name:
  name: "XRemit"

flutter:

  uses-material-design: true

  assets:
    - assets/BG/
    - assets/Clipart/
    - assets/flag/
    - assets/Icons/
    - assets/Logo/
    - assets/People/
    - assets/Payment Gateway/
